### PR TITLE
treat missing Accept field as */*

### PR DESCRIPTION
**Pull request by ghost**
Changes the behaviour on an absent Accept field to match the RFC 7231 ( http://tools.ietf.org/html/rfc7231#section-5.3.2 ).

### CODE REVIEW

**Comment by jchannon** [comment]
I think we still need tests for 406 as that can still be returned

Thanks

**Comment by ghost** [comment]
Didn't realize I was pulling out the only 406 tests, apologies! I'll update the PR (probably ~a few days).

**Comment by rickb777** [comment]
The delta proposed by this PR is one that I also included (i.e. copied) - see PR #21. The master contains this code so this PR can be closed as being no longer needed.

**Comment by jchannon** [comment]
Thanks both of you!

**Comment by rickb777** [comment]
Glad to be able to help. :)

**Pull request closed without merging**
