### PR TITLE
Added negotiate tests

### PR DESCRIPTION
**Pull request by jchannon**

### CODE REVIEW

**Comment by philcleveland** [comment]
I don't quite understand why it is necessary to order the processors.  Can you elaborate?

**Comment by jchannon** [comment]
If you have a processor that handles collection+json but if it's last in
the array the json processor will handle it before the custom one. Custom
ones should always be looped on first.

**Comment by philcleveland** [comment]
I wonder if a simpler solution is to not have default processors. Instead have the user pass in processors to New in prioritized order.  

In addition I also think that having CanProcess be more strict would help.  For instance instead of strings.HasSuffix(mediaRange, "json) it could be strings.EqualFold(mediaRange, "application/json"). Really the json processor shouldn't be used for collection+json right?

**Comment by jchannon** [comment]
Right but it could be used for patch json

Tbh the design of negotiator I've borrowed from Nancy :)

**Comment by philcleveland** [comment]
Gotcha

**Pull request merged**
