### PR TITLE
first test for json processor

### PR DESCRIPTION
**Pull request by jchannon**

### CODE REVIEW

**Comment by philcleveland** [comment]
I don't think the processor needs to be so loose.  Check out http://www.iana.org/assignments/media-types/media-types.xhtml for registered media types. For instance, I don't see text/json.  Maybe I am missing something though.

**Comment by jchannon** [comment]
One thing I've just thought of is we might need to insert custom processors
at the beginning of our processor slice. If someone had their own
collection+json processor and the default json processor was hit it would
say it could process it as it ends with +json but also the custom one could
say it could handle it.

I need to double check what Nancy does if there are two processors capable
of handling it. Does it call he first and the break the loop...

**Comment by jchannon** [comment]
Looks like it will loop over them and the first to return a response wins so this backs my idea up that we should insert custom processors at the front of the slice not append

https://github.com/NancyFx/Nancy/blob/45860c82e4df8e2d380997ddf1d19d61400fb145/src/Nancy/Responses/Negotiation/DefaultResponseNegotiator.cs#L273

**Comment by jchannon** [comment]
@pdoh00 see last commit :smile: 

I'd like to get this PR in and the comments i mentioned above I'll implement in another test PR

**Comment by philcleveland** [comment]
Looks good. :+1:

**Pull request merged**
